---
title: "M11 In Class Activity"
output: html_notebook
---
Exercise 11.1
```{r}
f1 <- 1
f2 <- 1
print(1)
print(1)
for (i in 1:8){
    f3 <- f1+f2
    f1 <- f2
    f2 <- f3
    print (f3)
}
```
Exercise 11.2
```{r}
fib <- function(n){
  vect <- numeric(n)
  vect[1] <- vect[2] <- 1
  for (i in 3:10){
    vect[i] <- vect[i-2]+vect[i-1]
  } 
  return (vect)
}

print(fib(10))
```
Exercise 11.3/11.4
```{r}
one_function <- function(x){
  if (x>=0 & x<=1){
    return (1)
  }else{
    return (0)
  }
}

one_function(1)
one_function(5)
one_function(-1)
```
Exercise 11.5
```{r}
first = letters[0:10]
last = LETTERS[16:26]
middle = LETTERS[22:24]
print(first)
print(last)
print(middle)
```
Exercise 11.6
```{r}
for (i in 1:100){
  if (i%%3==0 & i%%5==0){
    print("FizzBuzz")
  }else if (i%%3==0){
    print("Fizz")
  }else if (i%%5==0){
    print("Buzz")
  }
}
```
Exercise 11.7
```{r}
unique_func <- function(x){
  if (is.character(x)){
    x = strsplit(x,"")
    x = unlist(x)
  }
  print(unique(x))
}
unique_func("helloo")
unique_func(c(1,2,3,4,4,5,5))
```
Exercise 11.8
```{r}
vect <- c(1,2,3,4)
maximum <- max(vect)
minimum <- min(vect)
```
Exercise 11.9
```{r}
print(seq(20,50))
print(mean(20:50))
print(sum(20:50))
```
Exercise 11.10
```{r}
vect = c(1,2,3)
vect2 = c(2,3,4)
vect3 = c(5,6,7)
vect4 = c(9,10,11)
df = data.frame(vect,vect2,vect3,vect4)
```
Exercise 11.11
```{r}
plot(mtcars[,c('hp','cyl','mpg')])
```
